<?php

namespace Database\Seeders;

use App\Models\Journal;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class JournalSeeder extends Seeder
{
    public function run(): void
    {
        $adminUser = User::where('email', 'admin@editorialstandards.com')->first();
        if (!$adminUser) {
            $this->call(AdminUserSeeder::class);
            $adminUser = User::where('email', 'admin@editorialstandards.com')->first();
        }
        $userId = $adminUser->id;

        $journals = [
            // ── MULTIDISCIPLINARIAS ────────────────────────────────────────────
            ['title'=>'Nature','issn_print'=>'0028-0836','issn_online'=>'1476-4687','publisher'=>'Nature Publishing Group','publishing_institution'=>'Springer Nature','url'=>'https://www.nature.com/nature/','country_code'=>'GB','subject_areas'=>['Multidisciplinary'],'is_open_access'=>false,'access_type'=>'subscription','publication_languages'=>['en'],'start_year'=>1901,'peer_review_type'=>'single_blind','publication_frequency'=>'weekly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'Science','issn_print'=>'0036-8075','issn_online'=>'1095-9203','publisher'=>'American Association for the Advancement of Science','publishing_institution'=>'AAAS','url'=>'https://www.science.org/journal/science','country_code'=>'US','subject_areas'=>['Multidisciplinary'],'is_open_access'=>false,'access_type'=>'subscription','publication_languages'=>['en'],'start_year'=>1901,'peer_review_type'=>'single_blind','publication_frequency'=>'weekly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'PLOS ONE','issn_print'=>null,'issn_online'=>'1932-6203','publisher'=>'Public Library of Science','publishing_institution'=>'PLOS','url'=>'https://journals.plos.org/plosone/','country_code'=>'US','subject_areas'=>['Multidisciplinary'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['en'],'start_year'=>2006,'peer_review_type'=>'double_blind','publication_frequency'=>'continuous','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>true,'apc_amount'=>1705,'apc_currency'=>'USD','oai_base_url'=>'https://journals.plos.org/plosone/oai','oai_set_spec'=>null],
            ['title'=>'Scientific Reports','issn_print'=>null,'issn_online'=>'2045-2322','publisher'=>'Nature Publishing Group','publishing_institution'=>'Springer Nature','url'=>'https://www.nature.com/srep/','country_code'=>'GB','subject_areas'=>['Multidisciplinary'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['en'],'start_year'=>2011,'peer_review_type'=>'single_blind','publication_frequency'=>'continuous','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>true,'apc_amount'=>2190,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'Nature Communications','issn_print'=>null,'issn_online'=>'2041-1723','publisher'=>'Nature Publishing Group','publishing_institution'=>'Springer Nature','url'=>'https://www.nature.com/ncomms/','country_code'=>'GB','subject_areas'=>['Multidisciplinary'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['en'],'start_year'=>2010,'peer_review_type'=>'single_blind','publication_frequency'=>'continuous','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>true,'apc_amount'=>5690,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'Proceedings of the National Academy of Sciences','issn_print'=>'0027-8424','issn_online'=>'1091-6490','publisher'=>'National Academy of Sciences','publishing_institution'=>'NAS','url'=>'https://www.pnas.org/','country_code'=>'US','subject_areas'=>['Multidisciplinary'],'is_open_access'=>false,'access_type'=>'hybrid','publication_languages'=>['en'],'start_year'=>1914,'peer_review_type'=>'single_blind','publication_frequency'=>'weekly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>true,'apc_amount'=>1380,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'eLife','issn_print'=>null,'issn_online'=>'2050-084X','publisher'=>'eLife Sciences Publications','publishing_institution'=>'eLife Sciences','url'=>'https://elifesciences.org/','country_code'=>'GB','subject_areas'=>['Biology','Medicine'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['en'],'start_year'=>2012,'peer_review_type'=>'open','publication_frequency'=>'continuous','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>true,'apc_amount'=>2000,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],

            // ── MEDICINA / SALUD ───────────────────────────────────────────────
            ['title'=>'New England Journal of Medicine','issn_print'=>'0028-4793','issn_online'=>'1533-4406','publisher'=>'Massachusetts Medical Society','publishing_institution'=>'Massachusetts Medical Society','url'=>'https://www.nejm.org/','country_code'=>'US','subject_areas'=>['Medicine'],'is_open_access'=>false,'access_type'=>'subscription','publication_languages'=>['en'],'start_year'=>1901,'peer_review_type'=>'single_blind','publication_frequency'=>'weekly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'The Lancet','issn_print'=>'0140-6736','issn_online'=>'1474-547X','publisher'=>'Elsevier','publishing_institution'=>'Elsevier','url'=>'https://www.thelancet.com/','country_code'=>'GB','subject_areas'=>['Medicine'],'is_open_access'=>false,'access_type'=>'subscription','publication_languages'=>['en'],'start_year'=>1901,'peer_review_type'=>'single_blind','publication_frequency'=>'weekly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'JAMA – Journal of the American Medical Association','issn_print'=>'0098-7484','issn_online'=>'1538-3598','publisher'=>'American Medical Association','publishing_institution'=>'AMA','url'=>'https://jamanetwork.com/journals/jama','country_code'=>'US','subject_areas'=>['Medicine'],'is_open_access'=>false,'access_type'=>'subscription','publication_languages'=>['en'],'start_year'=>1901,'peer_review_type'=>'double_blind','publication_frequency'=>'weekly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'BMJ','issn_print'=>'0959-8138','issn_online'=>'1468-5833','publisher'=>'BMJ Publishing Group','publishing_institution'=>'British Medical Association','url'=>'https://www.bmj.com/','country_code'=>'GB','subject_areas'=>['Medicine'],'is_open_access'=>false,'access_type'=>'hybrid','publication_languages'=>['en'],'start_year'=>1901,'peer_review_type'=>'single_blind','publication_frequency'=>'weekly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>true,'apc_amount'=>4420,'apc_currency'=>'GBP','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'Annals of Internal Medicine','issn_print'=>'0003-4819','issn_online'=>'1539-3704','publisher'=>'American College of Physicians','publishing_institution'=>'ACP','url'=>'https://www.acpjournals.org/journal/aim','country_code'=>'US','subject_areas'=>['Internal Medicine'],'is_open_access'=>false,'access_type'=>'subscription','publication_languages'=>['en'],'start_year'=>1927,'peer_review_type'=>'double_blind','publication_frequency'=>'bimonthly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'PLOS Medicine','issn_print'=>'1549-1277','issn_online'=>'1549-1676','publisher'=>'Public Library of Science','publishing_institution'=>'PLOS','url'=>'https://journals.plos.org/plosmedicine/','country_code'=>'US','subject_areas'=>['Medicine','Public Health'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['en'],'start_year'=>2004,'peer_review_type'=>'double_blind','publication_frequency'=>'monthly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>true,'apc_amount'=>3900,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'BMJ Open','issn_print'=>null,'issn_online'=>'2044-6055','publisher'=>'BMJ Publishing Group','publishing_institution'=>'British Medical Association','url'=>'https://bmjopen.bmj.com/','country_code'=>'GB','subject_areas'=>['Medicine'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['en'],'start_year'=>2011,'peer_review_type'=>'double_blind','publication_frequency'=>'continuous','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>true,'apc_amount'=>2000,'apc_currency'=>'GBP','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'BMC Medicine','issn_print'=>null,'issn_online'=>'1741-7015','publisher'=>'BioMed Central','publishing_institution'=>'Springer Nature','url'=>'https://bmcmedicine.biomedcentral.com/','country_code'=>'GB','subject_areas'=>['Medicine'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['en'],'start_year'=>2003,'peer_review_type'=>'double_blind','publication_frequency'=>'continuous','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>true,'apc_amount'=>3290,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'World Psychiatry','issn_print'=>'1723-8617','issn_online'=>'2051-5545','publisher'=>'Wiley-Blackwell','publishing_institution'=>'World Psychiatric Association','url'=>'https://onlinelibrary.wiley.com/journal/20515545','country_code'=>'IT','subject_areas'=>['Psychiatry'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['en'],'start_year'=>2002,'peer_review_type'=>'double_blind','publication_frequency'=>'quarterly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'American Journal of Public Health','issn_print'=>'0090-0036','issn_online'=>'1541-0048','publisher'=>'American Public Health Association','publishing_institution'=>'APHA','url'=>'https://ajph.aphapublications.org/','country_code'=>'US','subject_areas'=>['Public Health'],'is_open_access'=>false,'access_type'=>'hybrid','publication_languages'=>['en'],'start_year'=>1911,'peer_review_type'=>'double_blind','publication_frequency'=>'monthly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>true,'apc_amount'=>3000,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'Environmental Health Perspectives','issn_print'=>'0091-6765','issn_online'=>'1552-9924','publisher'=>'National Institute of Environmental Health Sciences','publishing_institution'=>'NIEHS / NIH','url'=>'https://ehp.niehs.nih.gov/','country_code'=>'US','subject_areas'=>['Environmental Health','Public Health'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['en'],'start_year'=>1972,'peer_review_type'=>'double_blind','publication_frequency'=>'monthly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'BMC Public Health','issn_print'=>null,'issn_online'=>'1471-2458','publisher'=>'BioMed Central','publishing_institution'=>'Springer Nature','url'=>'https://bmcpublichealth.biomedcentral.com/','country_code'=>'GB','subject_areas'=>['Public Health'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['en'],'start_year'=>2001,'peer_review_type'=>'double_blind','publication_frequency'=>'continuous','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>true,'apc_amount'=>2290,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'JMIR Mental Health','issn_print'=>null,'issn_online'=>'2368-7959','publisher'=>'JMIR Publications','publishing_institution'=>'JMIR Publications','url'=>'https://mental.jmir.org/','country_code'=>'CA','subject_areas'=>['Mental Health','Digital Health'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['en'],'start_year'=>2014,'peer_review_type'=>'double_blind','publication_frequency'=>'continuous','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>true,'apc_amount'=>2500,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],

            // ── BIOLOGÍA / CIENCIAS NATURALES ──────────────────────────────────
            ['title'=>'Cell','issn_print'=>'0092-8674','issn_online'=>'1097-4172','publisher'=>'Cell Press / Elsevier','publishing_institution'=>'Elsevier','url'=>'https://www.cell.com/cell/home','country_code'=>'US','subject_areas'=>['Cell Biology','Molecular Biology'],'is_open_access'=>false,'access_type'=>'subscription','publication_languages'=>['en'],'start_year'=>1974,'peer_review_type'=>'single_blind','publication_frequency'=>'bimonthly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'Nucleic Acids Research','issn_print'=>'0305-1048','issn_online'=>'1362-4962','publisher'=>'Oxford University Press','publishing_institution'=>'Oxford University Press','url'=>'https://academic.oup.com/nar','country_code'=>'GB','subject_areas'=>['Biochemistry','Molecular Biology','Genetics'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['en'],'start_year'=>1974,'peer_review_type'=>'double_blind','publication_frequency'=>'bimonthly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>true,'apc_amount'=>3190,'apc_currency'=>'GBP','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'Genome Biology','issn_print'=>'1474-7596','issn_online'=>'1474-760X','publisher'=>'BioMed Central','publishing_institution'=>'Springer Nature','url'=>'https://genomebiology.biomedcentral.com/','country_code'=>'GB','subject_areas'=>['Genomics','Genetics'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['en'],'start_year'=>2000,'peer_review_type'=>'double_blind','publication_frequency'=>'continuous','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>true,'apc_amount'=>4490,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'Frontiers in Microbiology','issn_print'=>null,'issn_online'=>'1664-302X','publisher'=>'Frontiers Media','publishing_institution'=>'Frontiers Media SA','url'=>'https://www.frontiersin.org/journals/microbiology','country_code'=>'CH','subject_areas'=>['Microbiology'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['en'],'start_year'=>2010,'peer_review_type'=>'open','publication_frequency'=>'continuous','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>true,'apc_amount'=>2950,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'Ecology Letters','issn_print'=>'1461-023X','issn_online'=>'1461-0248','publisher'=>'Wiley-Blackwell','publishing_institution'=>'British Ecological Society / Wiley','url'=>'https://onlinelibrary.wiley.com/journal/14610248','country_code'=>'GB','subject_areas'=>['Ecology'],'is_open_access'=>false,'access_type'=>'hybrid','publication_languages'=>['en'],'start_year'=>1998,'peer_review_type'=>'double_blind','publication_frequency'=>'monthly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>true,'apc_amount'=>4690,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'Global Change Biology','issn_print'=>'1354-1013','issn_online'=>'1365-2486','publisher'=>'Wiley-Blackwell','publishing_institution'=>'Wiley','url'=>'https://onlinelibrary.wiley.com/journal/13652486','country_code'=>'GB','subject_areas'=>['Ecology','Environmental Sciences','Climate Change'],'is_open_access'=>false,'access_type'=>'hybrid','publication_languages'=>['en'],'start_year'=>1995,'peer_review_type'=>'double_blind','publication_frequency'=>'monthly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>true,'apc_amount'=>5090,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'Journal of Ecology','issn_print'=>'0022-0477','issn_online'=>'1365-2745','publisher'=>'Wiley-Blackwell','publishing_institution'=>'British Ecological Society','url'=>'https://besjournals.onlinelibrary.wiley.com/journal/13652745','country_code'=>'GB','subject_areas'=>['Ecology','Plant Biology'],'is_open_access'=>false,'access_type'=>'hybrid','publication_languages'=>['en'],'start_year'=>1913,'peer_review_type'=>'double_blind','publication_frequency'=>'bimonthly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'Methods in Ecology and Evolution','issn_print'=>null,'issn_online'=>'2041-210X','publisher'=>'Wiley-Blackwell','publishing_institution'=>'British Ecological Society','url'=>'https://besjournals.onlinelibrary.wiley.com/journal/2041210x','country_code'=>'GB','subject_areas'=>['Ecology','Evolutionary Biology'],'is_open_access'=>false,'access_type'=>'hybrid','publication_languages'=>['en'],'start_year'=>2010,'peer_review_type'=>'double_blind','publication_frequency'=>'monthly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>true,'apc_amount'=>4290,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'Malaria Journal','issn_print'=>null,'issn_online'=>'1475-2875','publisher'=>'BioMed Central','publishing_institution'=>'Springer Nature','url'=>'https://malariajournal.biomedcentral.com/','country_code'=>'GB','subject_areas'=>['Parasitology','Tropical Medicine','Infectious Diseases'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['en'],'start_year'=>2002,'peer_review_type'=>'double_blind','publication_frequency'=>'continuous','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>true,'apc_amount'=>2290,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],

            // ── QUÍMICA / FÍSICA / INGENIERÍA ──────────────────────────────────
            ['title'=>'Chemical Reviews','issn_print'=>'0009-2665','issn_online'=>'1520-6890','publisher'=>'American Chemical Society','publishing_institution'=>'ACS','url'=>'https://pubs.acs.org/journal/chreay','country_code'=>'US','subject_areas'=>['Chemistry'],'is_open_access'=>false,'access_type'=>'subscription','publication_languages'=>['en'],'start_year'=>1924,'peer_review_type'=>'double_blind','publication_frequency'=>'bimonthly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'Journal of the American Chemical Society','issn_print'=>'0002-7863','issn_online'=>'1520-5126','publisher'=>'American Chemical Society','publishing_institution'=>'ACS','url'=>'https://pubs.acs.org/journal/jacsat','country_code'=>'US','subject_areas'=>['Chemistry'],'is_open_access'=>false,'access_type'=>'subscription','publication_languages'=>['en'],'start_year'=>1901,'peer_review_type'=>'double_blind','publication_frequency'=>'weekly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'Angewandte Chemie International Edition','issn_print'=>'1433-7851','issn_online'=>'1521-3773','publisher'=>'Wiley-VCH','publishing_institution'=>'German Chemical Society (GDCh)','url'=>'https://onlinelibrary.wiley.com/journal/15213773','country_code'=>'DE','subject_areas'=>['Chemistry'],'is_open_access'=>false,'access_type'=>'hybrid','publication_languages'=>['en'],'start_year'=>1901,'peer_review_type'=>'double_blind','publication_frequency'=>'weekly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>true,'apc_amount'=>5200,'apc_currency'=>'EUR','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'Physical Review Letters','issn_print'=>'0031-9007','issn_online'=>'1079-7114','publisher'=>'American Physical Society','publishing_institution'=>'APS','url'=>'https://journals.aps.org/prl/','country_code'=>'US','subject_areas'=>['Physics'],'is_open_access'=>false,'access_type'=>'subscription','publication_languages'=>['en'],'start_year'=>1958,'peer_review_type'=>'single_blind','publication_frequency'=>'weekly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'ACS Nano','issn_print'=>'1936-0851','issn_online'=>'1936-086X','publisher'=>'American Chemical Society','publishing_institution'=>'ACS','url'=>'https://pubs.acs.org/journal/ancac3','country_code'=>'US','subject_areas'=>['Nanoscience','Nanotechnology','Materials Science'],'is_open_access'=>false,'access_type'=>'subscription','publication_languages'=>['en'],'start_year'=>2007,'peer_review_type'=>'double_blind','publication_frequency'=>'monthly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'Environmental Science & Technology','issn_print'=>'0013-936X','issn_online'=>'1520-5851','publisher'=>'American Chemical Society','publishing_institution'=>'ACS','url'=>'https://pubs.acs.org/journal/esthag','country_code'=>'US','subject_areas'=>['Environmental Science','Chemistry'],'is_open_access'=>false,'access_type'=>'subscription','publication_languages'=>['en'],'start_year'=>1967,'peer_review_type'=>'double_blind','publication_frequency'=>'bimonthly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'Sensors','issn_print'=>null,'issn_online'=>'1424-8220','publisher'=>'MDPI','publishing_institution'=>'MDPI AG','url'=>'https://www.mdpi.com/journal/sensors','country_code'=>'CH','subject_areas'=>['Engineering','Instrumentation','Physics'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['en'],'start_year'=>2001,'peer_review_type'=>'double_blind','publication_frequency'=>'continuous','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>true,'apc_amount'=>2600,'apc_currency'=>'CHF','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'IEEE Access','issn_print'=>null,'issn_online'=>'2169-3536','publisher'=>'IEEE','publishing_institution'=>'Institute of Electrical and Electronics Engineers','url'=>'https://ieeeaccess.ieee.org/','country_code'=>'US','subject_areas'=>['Engineering','Computer Science','Electrical Engineering'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['en'],'start_year'=>2013,'peer_review_type'=>'double_blind','publication_frequency'=>'continuous','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>true,'apc_amount'=>1750,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'Molecules','issn_print'=>null,'issn_online'=>'1420-3049','publisher'=>'MDPI','publishing_institution'=>'MDPI AG','url'=>'https://www.mdpi.com/journal/molecules','country_code'=>'CH','subject_areas'=>['Chemistry','Biochemistry'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['en'],'start_year'=>1996,'peer_review_type'=>'double_blind','publication_frequency'=>'continuous','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>true,'apc_amount'=>2700,'apc_currency'=>'CHF','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'Advanced Materials','issn_print'=>'0935-9648','issn_online'=>'1521-4095','publisher'=>'Wiley-VCH','publishing_institution'=>'Wiley-VCH Verlag GmbH','url'=>'https://onlinelibrary.wiley.com/journal/15214095','country_code'=>'DE','subject_areas'=>['Materials Science','Nanotechnology'],'is_open_access'=>false,'access_type'=>'subscription','publication_languages'=>['en'],'start_year'=>1989,'peer_review_type'=>'single_blind','publication_frequency'=>'weekly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'International Journal of Environmental Research and Public Health','issn_print'=>null,'issn_online'=>'1660-4601','publisher'=>'MDPI','publishing_institution'=>'MDPI AG','url'=>'https://www.mdpi.com/journal/ijerph','country_code'=>'CH','subject_areas'=>['Environmental Health','Public Health'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['en'],'start_year'=>2004,'peer_review_type'=>'double_blind','publication_frequency'=>'continuous','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>true,'apc_amount'=>2900,'apc_currency'=>'CHF','oai_base_url'=>null,'oai_set_spec'=>null],

            // ── CIENCIAS SOCIALES / PSICOLOGÍA ─────────────────────────────────
            ['title'=>'Frontiers in Psychology','issn_print'=>null,'issn_online'=>'1664-1078','publisher'=>'Frontiers Media','publishing_institution'=>'Frontiers Media SA','url'=>'https://www.frontiersin.org/journals/psychology','country_code'=>'CH','subject_areas'=>['Psychology'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['en'],'start_year'=>2010,'peer_review_type'=>'open','publication_frequency'=>'continuous','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>true,'apc_amount'=>2950,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'Scientometrics','issn_print'=>'0138-9130','issn_online'=>'1588-2861','publisher'=>'Springer','publishing_institution'=>'Springer Nature','url'=>'https://link.springer.com/journal/11192','country_code'=>'NL','subject_areas'=>['Library and Information Science','Scientometrics'],'is_open_access'=>false,'access_type'=>'hybrid','publication_languages'=>['en'],'start_year'=>1978,'peer_review_type'=>'double_blind','publication_frequency'=>'monthly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>true,'apc_amount'=>3290,'apc_currency'=>'EUR','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'El Profesional de la Información','issn_print'=>'1386-6710','issn_online'=>'1699-2407','publisher'=>'EPI SCP','publishing_institution'=>'Escola Superior de Biblioteconomia i Documentació','url'=>'https://www.elprofesionaldelainformacion.com/','country_code'=>'ES','subject_areas'=>['Library and Information Science','Communication'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['en','es'],'start_year'=>1992,'peer_review_type'=>'double_blind','publication_frequency'=>'bimonthly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'Latin American Research Review','issn_print'=>'0023-8791','issn_online'=>'1542-4278','publisher'=>'University of Pittsburgh Press','publishing_institution'=>'Latin American Studies Association','url'=>'https://larrlasa.org/','country_code'=>'US','subject_areas'=>['Latin American Studies','Social Sciences','Humanities'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['en','es','pt'],'start_year'=>1965,'peer_review_type'=>'double_blind','publication_frequency'=>'quarterly','has_ethics_policy'=>true,'adheres_to_cope'=>false,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],

            // ── EUROPA – ESPAÑA / PORTUGAL / ITALIA / FRANCE ──────────────────
            ['title'=>'Gaceta Sanitaria','issn_print'=>'0213-9111','issn_online'=>'1578-1283','publisher'=>'Sociedad Española de Salud Pública y Administración Sanitaria','publishing_institution'=>'SESPAS','url'=>'https://www.gacetasanitaria.org/','country_code'=>'ES','subject_areas'=>['Public Health','Health Policy'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['es','en'],'start_year'=>1987,'peer_review_type'=>'double_blind','publication_frequency'=>'bimonthly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'Revista Española de Cardiología','issn_print'=>'0300-8932','issn_online'=>'1579-2242','publisher'=>'Sociedad Española de Cardiología','publishing_institution'=>'Sociedad Española de Cardiología','url'=>'https://www.revespcardiol.org/','country_code'=>'ES','subject_areas'=>['Cardiology'],'is_open_access'=>false,'access_type'=>'subscription','publication_languages'=>['es','en'],'start_year'=>1947,'peer_review_type'=>'double_blind','publication_frequency'=>'monthly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'European Journal of Public Health','issn_print'=>'1101-1262','issn_online'=>'1464-360X','publisher'=>'Oxford University Press','publishing_institution'=>'European Public Health Association','url'=>'https://academic.oup.com/eurpub','country_code'=>'GB','subject_areas'=>['Public Health'],'is_open_access'=>false,'access_type'=>'hybrid','publication_languages'=>['en'],'start_year'=>1991,'peer_review_type'=>'double_blind','publication_frequency'=>'bimonthly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>true,'apc_amount'=>2500,'apc_currency'=>'GBP','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'International Journal of Epidemiology','issn_print'=>'0300-5771','issn_online'=>'1464-3685','publisher'=>'Oxford University Press','publishing_institution'=>'International Epidemiological Association','url'=>'https://academic.oup.com/ije','country_code'=>'GB','subject_areas'=>['Epidemiology','Public Health'],'is_open_access'=>false,'access_type'=>'hybrid','publication_languages'=>['en'],'start_year'=>1972,'peer_review_type'=>'double_blind','publication_frequency'=>'bimonthly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>true,'apc_amount'=>3800,'apc_currency'=>'GBP','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'Acta Médica Portuguesa','issn_print'=>'1646-0758','issn_online'=>'0001-7566','publisher'=>'Ordem dos Médicos','publishing_institution'=>'Ordem dos Médicos','url'=>'https://www.actamedicaportuguesa.com/','country_code'=>'PT','subject_areas'=>['Medicine'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['pt','en'],'start_year'=>1979,'peer_review_type'=>'double_blind','publication_frequency'=>'monthly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'Minerva Medica','issn_print'=>'0026-4806','issn_online'=>'1827-1898','publisher'=>'Edizioni Minerva Medica','publishing_institution'=>'Edizioni Minerva Medica','url'=>'https://www.minervamedica.it/en/journals/minerva-medica/','country_code'=>'IT','subject_areas'=>['Medicine','Internal Medicine'],'is_open_access'=>false,'access_type'=>'subscription','publication_languages'=>['en','it'],'start_year'=>1909,'peer_review_type'=>'double_blind','publication_frequency'=>'bimonthly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'Comptes Rendus Biologies','issn_print'=>'1631-0691','issn_online'=>'1768-3238','publisher'=>'Académie des sciences','publishing_institution'=>'Académie des sciences – Institut de France','url'=>'https://www.journals.elsevier.com/comptes-rendus-biologies','country_code'=>'FR','subject_areas'=>['Biology'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['en','fr'],'start_year'=>2002,'peer_review_type'=>'double_blind','publication_frequency'=>'continuous','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>true,'apc_amount'=>1200,'apc_currency'=>'EUR','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'Bioinformatics','issn_print'=>'1367-4803','issn_online'=>'1460-2059','publisher'=>'Oxford University Press','publishing_institution'=>'Oxford University Press','url'=>'https://academic.oup.com/bioinformatics','country_code'=>'GB','subject_areas'=>['Bioinformatics','Computational Biology'],'is_open_access'=>false,'access_type'=>'hybrid','publication_languages'=>['en'],'start_year'=>1985,'peer_review_type'=>'double_blind','publication_frequency'=>'bimonthly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>true,'apc_amount'=>3680,'apc_currency'=>'GBP','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'Journal of Infection in Developing Countries','issn_print'=>null,'issn_online'=>'1972-2680','publisher'=>'JIDC','publishing_institution'=>'Journal of Infection in Developing Countries','url'=>'https://jidc.org/','country_code'=>'IT','subject_areas'=>['Infectious Diseases','Tropical Medicine'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['en'],'start_year'=>2007,'peer_review_type'=>'double_blind','publication_frequency'=>'monthly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],

            // ── LATINOAMÉRICA – BRASIL ─────────────────────────────────────────
            ['title'=>'Revista de Saúde Pública','issn_print'=>'0034-8910','issn_online'=>'1518-8787','publisher'=>'Faculdade de Saúde Pública da Universidade de São Paulo','publishing_institution'=>'USP','url'=>'https://www.scielo.br/j/rsp/','country_code'=>'BR','subject_areas'=>['Public Health'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['pt','en'],'start_year'=>1967,'peer_review_type'=>'double_blind','publication_frequency'=>'continuous','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>'https://www.scielo.br/oai/scielo.php','oai_set_spec'=>'rsp'],
            ['title'=>'Memórias do Instituto Oswaldo Cruz','issn_print'=>'0074-0276','issn_online'=>'1678-8060','publisher'=>'Instituto Oswaldo Cruz','publishing_institution'=>'Fiocruz','url'=>'https://www.scielo.br/j/mioc/','country_code'=>'BR','subject_areas'=>['Parasitology','Microbiology','Tropical Medicine'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['en'],'start_year'=>1909,'peer_review_type'=>'double_blind','publication_frequency'=>'continuous','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>'https://www.scielo.br/oai/scielo.php','oai_set_spec'=>'mioc'],
            ['title'=>'Cadernos de Saúde Pública','issn_print'=>'0102-311X','issn_online'=>'1678-4464','publisher'=>'Escola Nacional de Saúde Pública Sergio Arouca','publishing_institution'=>'Fiocruz','url'=>'https://www.scielo.br/j/csp/','country_code'=>'BR','subject_areas'=>['Public Health','Epidemiology'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['pt','en','es'],'start_year'=>1985,'peer_review_type'=>'double_blind','publication_frequency'=>'continuous','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>'https://www.scielo.br/oai/scielo.php','oai_set_spec'=>'csp'],
            ['title'=>'Anais da Academia Brasileira de Ciências','issn_print'=>'0001-3765','issn_online'=>'1678-2690','publisher'=>'Academia Brasileira de Ciências','publishing_institution'=>'Academia Brasileira de Ciências','url'=>'https://www.scielo.br/j/aabc/','country_code'=>'BR','subject_areas'=>['Multidisciplinary'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['en','pt'],'start_year'=>1929,'peer_review_type'=>'double_blind','publication_frequency'=>'quarterly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>'https://www.scielo.br/oai/scielo.php','oai_set_spec'=>'aabc'],
            ['title'=>'Brazilian Journal of Biology','issn_print'=>'1519-6984','issn_online'=>'1678-4375','publisher'=>'Instituto Internacional de Ecologia','publishing_institution'=>'Instituto Internacional de Ecologia','url'=>'https://www.scielo.br/j/bjb/','country_code'=>'BR','subject_areas'=>['Biology','Ecology'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['en'],'start_year'=>1995,'peer_review_type'=>'double_blind','publication_frequency'=>'quarterly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>'https://www.scielo.br/oai/scielo.php','oai_set_spec'=>'bjb'],
            ['title'=>'Ciência Rural','issn_print'=>'0103-8478','issn_online'=>'1678-4596','publisher'=>'Universidade Federal de Santa Maria','publishing_institution'=>'UFSM','url'=>'https://www.scielo.br/j/cr/','country_code'=>'BR','subject_areas'=>['Agricultural Sciences','Veterinary Sciences'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['pt','en','es'],'start_year'=>1971,'peer_review_type'=>'double_blind','publication_frequency'=>'monthly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>'https://www.scielo.br/oai/scielo.php','oai_set_spec'=>'cr'],
            ['title'=>'Acta Amazonica','issn_print'=>'0044-5967','issn_online'=>'1809-4392','publisher'=>'Instituto Nacional de Pesquisas da Amazônia','publishing_institution'=>'INPA','url'=>'https://www.scielo.br/j/aa/','country_code'=>'BR','subject_areas'=>['Ecology','Environmental Sciences','Biodiversity'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['pt','en','es'],'start_year'=>1971,'peer_review_type'=>'double_blind','publication_frequency'=>'quarterly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>'https://www.scielo.br/oai/scielo.php','oai_set_spec'=>'aa'],
            ['title'=>'Scientia Agricola','issn_print'=>'0103-9016','issn_online'=>'1678-992X','publisher'=>'Universidade de São Paulo','publishing_institution'=>'USP / ESALQ','url'=>'https://www.scielo.br/j/sa/','country_code'=>'BR','subject_areas'=>['Agricultural Sciences','Food Sciences'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['en'],'start_year'=>1944,'peer_review_type'=>'double_blind','publication_frequency'=>'bimonthly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>'https://www.scielo.br/oai/scielo.php','oai_set_spec'=>'sa'],
            ['title'=>'Revista Brasileira de Farmacognosia','issn_print'=>'0102-695X','issn_online'=>'1981-528X','publisher'=>'Sociedade Brasileira de Farmacognosia','publishing_institution'=>'SBFar','url'=>'https://www.scielo.br/j/rbfar/','country_code'=>'BR','subject_areas'=>['Pharmacology','Natural Products'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['en','pt'],'start_year'=>1986,'peer_review_type'=>'double_blind','publication_frequency'=>'bimonthly','has_ethics_policy'=>true,'adheres_to_cope'=>false,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>'https://www.scielo.br/oai/scielo.php','oai_set_spec'=>'rbfar'],

            // ── LATINOAMÉRICA – MÉXICO ─────────────────────────────────────────
            ['title'=>'Salud Pública de México','issn_print'=>'0036-3634','issn_online'=>'1606-7916','publisher'=>'Instituto Nacional de Salud Pública','publishing_institution'=>'INSP','url'=>'https://saludpublica.mx/','country_code'=>'MX','subject_areas'=>['Public Health'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['es','en'],'start_year'=>1959,'peer_review_type'=>'double_blind','publication_frequency'=>'bimonthly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>'https://www.scielo.org.mx/oai/scielo.php','oai_set_spec'=>'spm'],
            ['title'=>'Archivos de Cardiología de México','issn_print'=>'1405-9940','issn_online'=>'1665-1731','publisher'=>'Sociedad Mexicana de Cardiología','publishing_institution'=>'Sociedad Mexicana de Cardiología','url'=>'https://www.archivoscardiologia.com/','country_code'=>'MX','subject_areas'=>['Cardiology'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['es','en'],'start_year'=>1930,'peer_review_type'=>'double_blind','publication_frequency'=>'quarterly','has_ethics_policy'=>true,'adheres_to_cope'=>false,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>'https://www.scielo.org.mx/oai/scielo.php','oai_set_spec'=>'acm'],
            ['title'=>'Revista Mexicana de Ciencias Políticas y Sociales','issn_print'=>'0185-1918','issn_online'=>'2448-492X','publisher'=>'Facultad de Ciencias Políticas y Sociales, UNAM','publishing_institution'=>'UNAM','url'=>'https://www.revistas.unam.mx/index.php/rmcpys','country_code'=>'MX','subject_areas'=>['Political Science','Social Sciences'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['es'],'start_year'=>1955,'peer_review_type'=>'double_blind','publication_frequency'=>'quarterly','has_ethics_policy'=>true,'adheres_to_cope'=>false,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],

            // ── LATINOAMÉRICA – COLOMBIA ───────────────────────────────────────
            ['title'=>'Biomédica','issn_print'=>'0120-4157','issn_online'=>'2590-7379','publisher'=>'Instituto Nacional de Salud','publishing_institution'=>'INS Colombia','url'=>'https://www.revistabiomedica.org/','country_code'=>'CO','subject_areas'=>['Medicine','Biomedical Sciences'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['es','en'],'start_year'=>1981,'peer_review_type'=>'double_blind','publication_frequency'=>'quarterly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>'https://www.scielo.org.co/oai/scielo.php','oai_set_spec'=>'bio'],
            ['title'=>'Revista Colombiana de Psiquiatría','issn_print'=>'0034-7450','issn_online'=>'1900-3862','publisher'=>'Asociación Colombiana de Psiquiatría','publishing_institution'=>'Asociación Colombiana de Psiquiatría','url'=>'https://www.elsevier.es/es-revista-revista-colombiana-psiquiatria-379','country_code'=>'CO','subject_areas'=>['Psychiatry','Mental Health'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['es','en'],'start_year'=>1962,'peer_review_type'=>'double_blind','publication_frequency'=>'quarterly','has_ethics_policy'=>true,'adheres_to_cope'=>false,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'Cuadernos de Desarrollo Rural','issn_print'=>'0122-1450','issn_online'=>'2215-7727','publisher'=>'Pontificia Universidad Javeriana','publishing_institution'=>'PUJ','url'=>'https://revistas.javeriana.edu.co/index.php/desarrolloRural','country_code'=>'CO','subject_areas'=>['Rural Development','Agricultural Sciences','Social Sciences'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['es','en'],'start_year'=>2004,'peer_review_type'=>'double_blind','publication_frequency'=>'biannual','has_ethics_policy'=>true,'adheres_to_cope'=>false,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'Revista Latinoamericana de Psicología','issn_print'=>'0120-0534','issn_online'=>'2145-4515','publisher'=>'Konrad Lorenz Fundación Universitaria','publishing_institution'=>'Konrad Lorenz Fundación Universitaria','url'=>'https://www.redalyc.org/revista.oa?id=805','country_code'=>'CO','subject_areas'=>['Psychology'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['es','en','pt'],'start_year'=>1969,'peer_review_type'=>'double_blind','publication_frequency'=>'quarterly','has_ethics_policy'=>true,'adheres_to_cope'=>false,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'Revista Colombiana de Estadística','issn_print'=>'0120-1751','issn_online'=>'2389-8976','publisher'=>'Universidad Nacional de Colombia','publishing_institution'=>'Departamento de Estadística, UNAL','url'=>'https://revistas.unal.edu.co/index.php/estad','country_code'=>'CO','subject_areas'=>['Statistics','Mathematics'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['es','en'],'start_year'=>1978,'peer_review_type'=>'double_blind','publication_frequency'=>'biannual','has_ethics_policy'=>true,'adheres_to_cope'=>false,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],

            // ── LATINOAMÉRICA – ARGENTINA ──────────────────────────────────────
            ['title'=>'Medicina (Buenos Aires)','issn_print'=>'0025-7680','issn_online'=>'1669-9106','publisher'=>'Fundación Revista Medicina','publishing_institution'=>'Fundación Revista Medicina','url'=>'https://www.medicinabuenosaires.com/','country_code'=>'AR','subject_areas'=>['Medicine'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['es','en'],'start_year'=>1939,'peer_review_type'=>'double_blind','publication_frequency'=>'bimonthly','has_ethics_policy'=>true,'adheres_to_cope'=>false,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>'https://www.scielo.org.ar/oai/scielo.php','oai_set_spec'=>'medba'],
            ['title'=>'Salud Colectiva','issn_print'=>'1669-2381','issn_online'=>'1851-8265','publisher'=>'Universidad Nacional de Lanús','publishing_institution'=>'UNLa','url'=>'https://salud-colectiva.unla.edu.ar/','country_code'=>'AR','subject_areas'=>['Public Health','Social Medicine'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['es','en'],'start_year'=>2005,'peer_review_type'=>'double_blind','publication_frequency'=>'quarterly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],

            // ── LATINOAMÉRICA – CHILE ──────────────────────────────────────────
            ['title'=>'Revista Médica de Chile','issn_print'=>'0034-9887','issn_online'=>'0717-6163','publisher'=>'Sociedad Médica de Santiago','publishing_institution'=>'Sociedad Médica de Santiago','url'=>'https://www.revistamedicadechile.cl/','country_code'=>'CL','subject_areas'=>['Medicine'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['es','en'],'start_year'=>1901,'peer_review_type'=>'double_blind','publication_frequency'=>'monthly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>'https://www.scielo.cl/oai/scielo.php','oai_set_spec'=>'rmc'],
            ['title'=>'Chungara, Revista de Antropología Chilena','issn_print'=>'0716-1182','issn_online'=>'0717-7356','publisher'=>'Universidad de Tarapacá','publishing_institution'=>'Universidad de Tarapacá','url'=>'https://chungara.cl/','country_code'=>'CL','subject_areas'=>['Anthropology','Archaeology'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['es','en'],'start_year'=>1972,'peer_review_type'=>'double_blind','publication_frequency'=>'quarterly','has_ethics_policy'=>true,'adheres_to_cope'=>false,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'Revista EURE','issn_print'=>'0250-7161','issn_online'=>'0717-6236','publisher'=>'Pontificia Universidad Católica de Chile','publishing_institution'=>'PUC Chile / Instituto de Estudios Urbanos','url'=>'https://www.eure.cl/','country_code'=>'CL','subject_areas'=>['Urban Studies','Regional Planning'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['es','en'],'start_year'=>1971,'peer_review_type'=>'double_blind','publication_frequency'=>'quarterly','has_ethics_policy'=>true,'adheres_to_cope'=>false,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'Revista Chilena de Historia Natural','issn_print'=>'0016-5301','issn_online'=>'0717-6317','publisher'=>'Sociedad de Biología de Chile','publishing_institution'=>'Sociedad de Biología de Chile','url'=>'https://rchn.biologiachile.cl/','country_code'=>'CL','subject_areas'=>['Natural History','Biology','Ecology'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['es','en'],'start_year'=>1901,'peer_review_type'=>'double_blind','publication_frequency'=>'continuous','has_ethics_policy'=>true,'adheres_to_cope'=>false,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],

            // ── LATINOAMÉRICA – PERÚ ───────────────────────────────────────────
            ['title'=>'Revista Peruana de Medicina Experimental y Salud Pública','issn_print'=>'1726-4634','issn_online'=>'1726-4642','publisher'=>'Instituto Nacional de Salud del Perú','publishing_institution'=>'INS Perú','url'=>'https://rpmesp.ins.gob.pe/','country_code'=>'PE','subject_areas'=>['Medicine','Public Health','Tropical Medicine'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['es','en'],'start_year'=>1942,'peer_review_type'=>'double_blind','publication_frequency'=>'quarterly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>'https://www.scielo.org.pe/oai/scielo.php','oai_set_spec'=>'rins'],
            ['title'=>'Revista de Investigaciones Veterinarias del Perú','issn_print'=>'1609-9117','issn_online'=>'1682-3419','publisher'=>'Universidad Nacional Mayor de San Marcos','publishing_institution'=>'UNMSM','url'=>'https://revistasinvestigacion.unmsm.edu.pe/index.php/veterinaria','country_code'=>'PE','subject_areas'=>['Veterinary Sciences'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['es','en'],'start_year'=>1990,'peer_review_type'=>'double_blind','publication_frequency'=>'quarterly','has_ethics_policy'=>true,'adheres_to_cope'=>false,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],

            // ── LATINOAMÉRICA – CUBA, VENEZUELA, CR, UY, EC ───────────────────
            ['title'=>'Revista Cubana de Medicina Tropical','issn_print'=>'0375-0760','issn_online'=>'1561-3054','publisher'=>'Instituto de Medicina Tropical Pedro Kourí','publishing_institution'=>'IPK','url'=>'http://www.revmedtropical.sld.cu/','country_code'=>'CU','subject_areas'=>['Tropical Medicine','Parasitology'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['es','en'],'start_year'=>1949,'peer_review_type'=>'double_blind','publication_frequency'=>'quarterly','has_ethics_policy'=>true,'adheres_to_cope'=>false,'has_antiplagiarism_policy'=>true,'assigns_doi'=>false,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>'https://www.scielo.sld.cu/oai/scielo.php','oai_set_spec'=>'rmt'],
            ['title'=>'Pastos y Forrajes','issn_print'=>'0864-0394','issn_online'=>'2078-8452','publisher'=>'Estación Experimental de Pastos y Forrajes Indio Hatuey','publishing_institution'=>'EEPF Indio Hatuey','url'=>'http://scielo.sld.cu/scielo.php?script=sci_serial&pid=0864-0394','country_code'=>'CU','subject_areas'=>['Agronomy','Animal Husbandry'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['es','en'],'start_year'=>1978,'peer_review_type'=>'double_blind','publication_frequency'=>'quarterly','has_ethics_policy'=>true,'adheres_to_cope'=>false,'has_antiplagiarism_policy'=>false,'assigns_doi'=>false,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>'https://www.scielo.sld.cu/oai/scielo.php','oai_set_spec'=>'pf'],
            ['title'=>'Investigación Clínica','issn_print'=>'0535-5133','issn_online'=>'2477-9393','publisher'=>'Universidad del Zulia','publishing_institution'=>'Universidad del Zulia','url'=>'https://produccioncientificaluz.org/index.php/investigacion','country_code'=>'VE','subject_areas'=>['Medicine','Clinical Research'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['es','en'],'start_year'=>1960,'peer_review_type'=>'double_blind','publication_frequency'=>'quarterly','has_ethics_policy'=>true,'adheres_to_cope'=>false,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'Archivos Latinoamericanos de Nutrición','issn_print'=>'0004-0622','issn_online'=>'2309-5806','publisher'=>'Sociedad Latinoamericana de Nutrición','publishing_institution'=>'SLAN','url'=>'https://www.alanrevista.org/','country_code'=>'VE','subject_areas'=>['Nutrition','Food Sciences'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['es','en'],'start_year'=>1951,'peer_review_type'=>'double_blind','publication_frequency'=>'quarterly','has_ethics_policy'=>true,'adheres_to_cope'=>false,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'Interciencia','issn_print'=>'0378-1844','issn_online'=>'0378-1844','publisher'=>'Asociación Interciencia','publishing_institution'=>'Asociación Interciencia','url'=>'https://www.interciencia.net/','country_code'=>'VE','subject_areas'=>['Multidisciplinary','Natural Sciences','Technology'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['es','en','pt'],'start_year'=>1976,'peer_review_type'=>'double_blind','publication_frequency'=>'monthly','has_ethics_policy'=>true,'adheres_to_cope'=>false,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'Revista de Biología Tropical','issn_print'=>'0034-7744','issn_online'=>'2215-2075','publisher'=>'Universidad de Costa Rica','publishing_institution'=>'UCR','url'=>'https://revistas.ucr.ac.cr/index.php/rbt','country_code'=>'CR','subject_areas'=>['Biology','Ecology','Tropical Biology'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['es','en'],'start_year'=>1953,'peer_review_type'=>'double_blind','publication_frequency'=>'quarterly','has_ethics_policy'=>true,'adheres_to_cope'=>false,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'Agrociencia Uruguay','issn_print'=>'1510-0839','issn_online'=>'2301-1548','publisher'=>'Universidad de la República','publishing_institution'=>'Facultad de Agronomía, UdelaR','url'=>'https://agrocienciauruguay.uy/','country_code'=>'UY','subject_areas'=>['Agricultural Sciences','Agronomy'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['es','en','pt'],'start_year'=>1997,'peer_review_type'=>'double_blind','publication_frequency'=>'quarterly','has_ethics_policy'=>true,'adheres_to_cope'=>false,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'Revista Ecuatoriana de Neurología','issn_print'=>'1019-8113','issn_online'=>'2631-2581','publisher'=>'Sociedad Ecuatoriana de Neurología','publishing_institution'=>'Sociedad Ecuatoriana de Neurología','url'=>'http://revecuatneurol.com/','country_code'=>'EC','subject_areas'=>['Neurology'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['es','en'],'start_year'=>1992,'peer_review_type'=>'double_blind','publication_frequency'=>'quarterly','has_ethics_policy'=>true,'adheres_to_cope'=>false,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],

            // ── ASIA ───────────────────────────────────────────────────────────
            ['title'=>'Chinese Medical Journal','issn_print'=>'0366-6999','issn_online'=>'2542-5641','publisher'=>'Chinese Medical Association','publishing_institution'=>'Chinese Medical Association','url'=>'https://journals.lww.com/cmj/','country_code'=>'CN','subject_areas'=>['Medicine'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['en'],'start_year'=>1901,'peer_review_type'=>'double_blind','publication_frequency'=>'bimonthly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>true,'apc_amount'=>2000,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'Cell Research','issn_print'=>'1001-0602','issn_online'=>'1748-7838','publisher'=>'Springer Nature','publishing_institution'=>'Chinese Academy of Sciences / Shanghai Institutes for Biological Sciences','url'=>'https://www.nature.com/cr/','country_code'=>'CN','subject_areas'=>['Cell Biology','Molecular Biology'],'is_open_access'=>false,'access_type'=>'hybrid','publication_languages'=>['en'],'start_year'=>1990,'peer_review_type'=>'single_blind','publication_frequency'=>'monthly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>true,'apc_amount'=>9900,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'Indian Journal of Medical Research','issn_print'=>'0971-5916','issn_online'=>'0975-9174','publisher'=>'Indian Council of Medical Research','publishing_institution'=>'ICMR','url'=>'https://www.ijmr.org.in/','country_code'=>'IN','subject_areas'=>['Medicine','Biomedical Sciences'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['en'],'start_year'=>1913,'peer_review_type'=>'double_blind','publication_frequency'=>'monthly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'Journal of Biosciences','issn_print'=>'0250-5991','issn_online'=>'0973-7138','publisher'=>'Springer India','publishing_institution'=>'Indian Academy of Sciences','url'=>'https://www.ias.ac.in/jbiosci/','country_code'=>'IN','subject_areas'=>['Biology','Life Sciences'],'is_open_access'=>false,'access_type'=>'subscription','publication_languages'=>['en'],'start_year'=>1979,'peer_review_type'=>'double_blind','publication_frequency'=>'quarterly','has_ethics_policy'=>true,'adheres_to_cope'=>false,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'Journal of Korean Medical Science','issn_print'=>'1011-8934','issn_online'=>'1598-6357','publisher'=>'Korean Academy of Medical Sciences','publishing_institution'=>'KAMS','url'=>'https://jkms.org/','country_code'=>'KR','subject_areas'=>['Medicine'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['en'],'start_year'=>1986,'peer_review_type'=>'double_blind','publication_frequency'=>'weekly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>true,'apc_amount'=>600,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'Korean Journal of Internal Medicine','issn_print'=>'1226-3303','issn_online'=>'2005-6648','publisher'=>'Korean Association of Internal Medicine','publishing_institution'=>'KAIM','url'=>'https://kjim.org/','country_code'=>'KR','subject_areas'=>['Internal Medicine'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['en'],'start_year'=>1986,'peer_review_type'=>'double_blind','publication_frequency'=>'bimonthly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'Turkish Journal of Medical Sciences','issn_print'=>'1300-0144','issn_online'=>'1303-6165','publisher'=>'TÜBİTAK','publishing_institution'=>'The Scientific and Technological Research Council of Turkey','url'=>'https://journals.tubitak.gov.tr/medical/','country_code'=>'TR','subject_areas'=>['Medicine'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['en'],'start_year'=>1971,'peer_review_type'=>'double_blind','publication_frequency'=>'bimonthly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'Iranian Journal of Public Health','issn_print'=>'2251-6085','issn_online'=>'2251-6093','publisher'=>'Tehran University of Medical Sciences','publishing_institution'=>'Tehran University of Medical Sciences','url'=>'https://ijph.tums.ac.ir/','country_code'=>'IR','subject_areas'=>['Public Health'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['en'],'start_year'=>1972,'peer_review_type'=>'double_blind','publication_frequency'=>'monthly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'Japanese Journal of Clinical Oncology','issn_print'=>'0368-2811','issn_online'=>'1465-3621','publisher'=>'Oxford University Press','publishing_institution'=>'Japanese Society of Clinical Oncology','url'=>'https://academic.oup.com/jjco','country_code'=>'JP','subject_areas'=>['Oncology'],'is_open_access'=>false,'access_type'=>'subscription','publication_languages'=>['en'],'start_year'=>1971,'peer_review_type'=>'double_blind','publication_frequency'=>'monthly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'Pakistan Journal of Medical Sciences','issn_print'=>'1682-024X','issn_online'=>'1681-715X','publisher'=>'Professional Medical Publications','publishing_institution'=>'Professional Medical Publications','url'=>'https://www.pjms.com.pk/','country_code'=>'PK','subject_areas'=>['Medicine'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['en'],'start_year'=>1984,'peer_review_type'=>'double_blind','publication_frequency'=>'bimonthly','has_ethics_policy'=>true,'adheres_to_cope'=>false,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'Asia Pacific Journal of Clinical Nutrition','issn_print'=>'0964-7058','issn_online'=>'1440-6047','publisher'=>'HEC Press','publishing_institution'=>'Asia Pacific Clinical Nutrition Society','url'=>'http://apjcn.nhri.org.tw/','country_code'=>'AU','subject_areas'=>['Nutrition','Clinical Medicine'],'is_open_access'=>false,'access_type'=>'subscription','publication_languages'=>['en'],'start_year'=>1992,'peer_review_type'=>'double_blind','publication_frequency'=>'quarterly','has_ethics_policy'=>true,'adheres_to_cope'=>false,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],

            // ── ÁFRICA / OCEANÍA ───────────────────────────────────────────────
            ['title'=>'South African Medical Journal','issn_print'=>'0256-9574','issn_online'=>'2078-5135','publisher'=>'Health & Medical Publishing Group','publishing_institution'=>'South African Medical Association','url'=>'https://samj.org.za/','country_code'=>'ZA','subject_areas'=>['Medicine'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['en'],'start_year'=>1901,'peer_review_type'=>'double_blind','publication_frequency'=>'monthly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'Nigerian Journal of Clinical Practice','issn_print'=>'1119-3077','issn_online'=>'2229-7731','publisher'=>'Medknow Publications','publishing_institution'=>'Medical and Dental Consultants Association of Nigeria','url'=>'https://www.njcponline.com/','country_code'=>'NG','subject_areas'=>['Medicine','Clinical Practice'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['en'],'start_year'=>1998,'peer_review_type'=>'double_blind','publication_frequency'=>'bimonthly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'East African Medical Journal','issn_print'=>'0012-835X','issn_online'=>null,'publisher'=>'Kenya Medical Association','publishing_institution'=>'Kenya Medical Association','url'=>'http://www.eamj.or.ke/','country_code'=>'KE','subject_areas'=>['Medicine','Tropical Medicine'],'is_open_access'=>false,'access_type'=>'subscription','publication_languages'=>['en'],'start_year'=>1923,'peer_review_type'=>'double_blind','publication_frequency'=>'monthly','has_ethics_policy'=>true,'adheres_to_cope'=>false,'has_antiplagiarism_policy'=>false,'assigns_doi'=>false,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'Egyptian Journal of Aquatic Research','issn_print'=>'1687-4285','issn_online'=>'1687-4293','publisher'=>'National Institute of Oceanography and Fisheries','publishing_institution'=>'National Institute of Oceanography and Fisheries of Egypt','url'=>'https://www.sciencedirect.com/journal/egyptian-journal-of-aquatic-research','country_code'=>'EG','subject_areas'=>['Marine Sciences','Aquatic Biology','Environmental Sciences'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['en'],'start_year'=>1975,'peer_review_type'=>'double_blind','publication_frequency'=>'quarterly','has_ethics_policy'=>true,'adheres_to_cope'=>false,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'Medical Journal of Australia','issn_print'=>'0025-729X','issn_online'=>'1326-5377','publisher'=>'AMPCo','publishing_institution'=>'Australian Medical Association','url'=>'https://www.mja.com.au/','country_code'=>'AU','subject_areas'=>['Medicine'],'is_open_access'=>false,'access_type'=>'subscription','publication_languages'=>['en'],'start_year'=>1914,'peer_review_type'=>'double_blind','publication_frequency'=>'bimonthly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'Australian and New Zealand Journal of Public Health','issn_print'=>'1326-0200','issn_online'=>'1753-6405','publisher'=>'Wiley-Blackwell','publishing_institution'=>'Public Health Association Australia','url'=>'https://onlinelibrary.wiley.com/journal/17536405','country_code'=>'AU','subject_areas'=>['Public Health'],'is_open_access'=>false,'access_type'=>'subscription','publication_languages'=>['en'],'start_year'=>1977,'peer_review_type'=>'double_blind','publication_frequency'=>'bimonthly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
            ['title'=>'New Zealand Medical Journal','issn_print'=>'0028-8446','issn_online'=>'1175-8716','publisher'=>'New Zealand Medical Association','publishing_institution'=>'NZMA','url'=>'https://www.nzma.org.nz/journal/','country_code'=>'NZ','subject_areas'=>['Medicine'],'is_open_access'=>true,'access_type'=>'open_access','publication_languages'=>['en'],'start_year'=>1901,'peer_review_type'=>'double_blind','publication_frequency'=>'bimonthly','has_ethics_policy'=>true,'adheres_to_cope'=>true,'has_antiplagiarism_policy'=>true,'assigns_doi'=>true,'charges_apc'=>false,'apc_amount'=>null,'apc_currency'=>'USD','oai_base_url'=>null,'oai_set_spec'=>null],
        ];

        foreach ($journals as $data) {
            $oai_base_url = $data['oai_base_url'] ?? null;
            $oai_set_spec = $data['oai_set_spec'] ?? null;
            unset($data['oai_base_url'], $data['oai_set_spec']);

            Journal::updateOrCreate(
                ['title' => $data['title']],
                array_merge($data, [
                    'user_id'                 => $userId,
                    'slug'                    => Str::slug($data['title']),
                    'status'                  => 'listed',
                    'listed_at'               => now(),
                    'target_audience'         => ['Academic', 'Researchers'],
                    'description'             => "Revista científica publicada por {$data['publisher']}.",
                    'editorial_board_visible' => true,
                    'current_score'           => null,
                    'evaluated_at'            => null,
                    'oai_base_url'            => $oai_base_url,
                    'oai_set_spec'            => $oai_set_spec,
                    'oai_metadata_prefix'     => 'oai_dc',
                ])
            );
        }

        $this->command->info('JournalSeeder: ' . count($journals) . ' revistas insertadas/actualizadas.');
    }
}
