<?php

namespace Database\Seeders;

use App\Models\Journal;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class JournalSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $adminUser = User::where('email', 'admin@editorialstandards.com')->first();
        
        if (!$adminUser) {
            $this->call(AdminUserSeeder::class);
            $adminUser = User::where('email', 'admin@editorialstandards.com')->first();
        }

        $userId = $adminUser->id;


        $journals = [
            [
                'title' => 'Nature',
                'issn_print' => '0028-0836',
                'issn_online' => '1476-4687',
                'publisher' => 'Nature Publishing Group',
                'url' => 'https://www.nature.com/nature/',
                'country_code' => 'GB',
                'subject_areas' => ['Multidisciplinary'],
                'is_open_access' => false,
                'oai_base_url' => 'https://oai.crossref.org/oai.v2',
                'oai_set_spec' => 'issn:0028-0836',
                'oai_metadata_prefix' => 'oai_dc',
            ],
            [
                'title' => 'Science',
                'issn_print' => '0036-8075',
                'issn_online' => '1095-9203',
                'publisher' => 'American Association for the Advancement of Science',
                'url' => 'https://www.science.org/journal/science',
                'country_code' => 'US',
                'subject_areas' => ['Multidisciplinary'],
                'is_open_access' => false,
                'oai_base_url' => 'https://oai.crossref.org/oai.v2',
                'oai_set_spec' => 'issn:0036-8075',
                'oai_metadata_prefix' => 'oai_dc',
            ],
            [
                'title' => 'The Lancet',
                'issn_print' => '0140-6736',
                'issn_online' => '1474-547X',
                'publisher' => 'Elsevier',
                'url' => 'https://www.thelancet.com/',
                'country_code' => 'GB',
                'subject_areas' => ['Medicine'],
                'is_open_access' => false,
                'oai_base_url' => 'https://oai.crossref.org/oai.v2',
                'oai_set_spec' => 'issn:0140-6736',
                'oai_metadata_prefix' => 'oai_dc',
            ],
            [
                'title' => 'JAMA',
                'issn_print' => '0098-7484',
                'issn_online' => '1538-3598',
                'publisher' => 'American Medical Association',
                'url' => 'https://jamanetwork.com/journals/jama',
                'country_code' => 'US',
                'subject_areas' => ['Medicine'],
                'is_open_access' => false,
                'oai_base_url' => 'https://oai.crossref.org/oai.v2',
                'oai_set_spec' => 'issn:0098-7484',
                'oai_metadata_prefix' => 'oai_dc',
            ],
            [
                'title' => 'PLOS ONE',
                'issn_print' => null,
                'issn_online' => '1932-6203',
                'publisher' => 'Public Library of Science',
                'url' => 'https://journals.plos.org/plosone/',
                'country_code' => 'US',
                'subject_areas' => ['Multidisciplinary'],
                'is_open_access' => true,
                'oai_base_url' => 'https://journals.plos.org/plosone/oai',
                'oai_set_spec' => null,
                'oai_metadata_prefix' => 'oai_dc',
            ],
            [
                'title' => 'Scientific Reports',
                'issn_print' => null,
                'issn_online' => '2045-2322',
                'publisher' => 'Nature Publishing Group',
                'url' => 'https://www.nature.com/srep/',
                'country_code' => 'GB',
                'subject_areas' => ['Multidisciplinary'],
                'is_open_access' => true,
                'oai_base_url' => 'https://oai.crossref.org/oai.v2',
                'oai_set_spec' => 'issn:2045-2322',
                'oai_metadata_prefix' => 'oai_dc',
            ],
            [
                'title' => 'Advanced Materials',
                'issn_print' => '0935-9648',
                'issn_online' => '1521-4095',
                'publisher' => 'Wiley-VCH',
                'url' => 'https://onlinelibrary.wiley.com/journal/15214095',
                'country_code' => 'DE',
                'subject_areas' => ['Materials Science'],
                'is_open_access' => false,
                'oai_base_url' => 'https://oai.crossref.org/oai.v2',
                'oai_set_spec' => 'issn:0935-9648',
                'oai_metadata_prefix' => 'oai_dc',
            ],
            [
                'title' => 'Chemical Reviews',
                'issn_print' => '0009-2665',
                'issn_online' => '1520-6890',
                'publisher' => 'American Chemical Society',
                'url' => 'https://pubs.acs.org/journal/chreay',
                'country_code' => 'US',
                'subject_areas' => ['Chemistry'],
                'is_open_access' => false,
                'oai_base_url' => 'https://oai.crossref.org/oai.v2',
                'oai_set_spec' => 'issn:0009-2665',
                'oai_metadata_prefix' => 'oai_dc',
            ],
            [
                'title' => 'World Psychiatry',
                'issn_print' => '1723-8617',
                'issn_online' => '2051-5545',
                'publisher' => 'Wiley-Blackwell',
                'url' => 'https://onlinelibrary.wiley.com/journal/20515545',
                'country_code' => 'IT',
                'subject_areas' => ['Psychiatry'],
                'is_open_access' => true,
                'oai_base_url' => 'https://oai.crossref.org/oai.v2',
                'oai_set_spec' => 'issn:1723-8617',
                'oai_metadata_prefix' => 'oai_dc',
            ],
            [
                'title' => 'Nucleic Acids Research',
                'issn_print' => '0305-1048',
                'issn_online' => '1362-4962',
                'publisher' => 'Oxford University Press',
                'url' => 'https://academic.oup.com/nar',
                'country_code' => 'GB',
                'subject_areas' => ['Biochemistry', 'Genetics', 'Molecular Biology'],
                'is_open_access' => true,
                'oai_base_url' => 'https://oai.crossref.org/oai.v2',
                'oai_set_spec' => 'issn:0305-1048',
                'oai_metadata_prefix' => 'oai_dc',
            ],
            [
                'title' => 'European Journal of Chemistry',
                'issn_print' => '2153-2249',
                'issn_online' => '2153-2257',
                'publisher' => 'Atlanta Publishing House',
                'url' => 'https://www.eurjchem.com/index.php/eurjchem',
                'country_code' => 'US',
                'subject_areas' => ['Chemistry'],
                'is_open_access' => true,
                'oai_base_url' => 'https://www.eurjchem.com/index.php/eurjchem/oai',
                'oai_set_spec' => 'eurjchem',
                'oai_metadata_prefix' => 'oai_dc',
            ],
            [
                'title' => 'Insights in Biology and Medicine',
                'issn_print' => null,
                'issn_online' => '2575-1212',
                'publisher' => 'Heighten Publications',
                'url' => 'https://www.biologymedjournal.com/',
                'country_code' => 'US',
                'subject_areas' => ['Biology', 'Medicine'],
                'is_open_access' => true,
                'oai_base_url' => 'https://www.biologymedjournal.com/oai',
                'oai_set_spec' => null,
                'oai_metadata_prefix' => 'oai_dc',
            ],
            [
                'title' => 'Archives of Food and Nutritional Science',
                'issn_print' => null,
                'issn_online' => '2575-0194',
                'publisher' => 'Heighten Publications',
                'url' => 'https://www.foodscijournal.com/index.php/afns',
                'country_code' => 'US',
                'subject_areas' => ['Food Science', 'Nutrition'],
                'is_open_access' => true,
                'oai_base_url' => 'https://www.foodscijournal.com/index.php/afns/oai',
                'oai_set_spec' => 'afns',
                'oai_metadata_prefix' => 'oai_dc',
            ],
            [
                'title' => 'Journal of Community Medicine and Health Solutions',
                'issn_print' => null,
                'issn_online' => '2736-1322',
                'publisher' => 'Heighten Publications',
                'url' => 'https://www.communitymedjournal.com/index.php/jcmhs',
                'country_code' => 'US',
                'subject_areas' => ['Community Medicine', 'Health'],
                'is_open_access' => true,
                'oai_base_url' => 'https://www.communitymedjournal.com/index.php/jcmhs/oai',
                'oai_set_spec' => 'jcmhs',
                'oai_metadata_prefix' => 'oai_dc',
            ],
            [
                'title' => 'Brazilian Journal of Biology',
                'issn_print' => '1519-6984',
                'issn_online' => '1678-4375',
                'publisher' => 'Instituto Internacional de Ecologia',
                'url' => 'https://www.scielo.br/j/bjb/',
                'country_code' => 'BR',
                'subject_areas' => ['Biology'],
                'is_open_access' => true,
                'oai_base_url' => 'https://www.scielo.br/oai/scielo.php',
                'oai_set_spec' => 'bjb',
                'oai_metadata_prefix' => 'oai_dc',
            ],
            [
                'title' => 'Revista de Saúde Pública',
                'issn_print' => '0034-8910',
                'issn_online' => '1518-8787',
                'publisher' => 'Faculdade de Saúde Pública da USP',
                'url' => 'https://www.scielo.br/j/rsp/',
                'country_code' => 'BR',
                'subject_areas' => ['Public Health'],
                'is_open_access' => true,
                'oai_base_url' => 'https://www.scielo.br/oai/scielo.php',
                'oai_set_spec' => 'rsp',
                'oai_metadata_prefix' => 'oai_dc',
            ],
            [
                'title' => 'Memórias do Instituto Oswaldo Cruz',
                'issn_print' => '0074-0276',
                'issn_online' => '1678-8060',
                'publisher' => 'Instituto Oswaldo Cruz',
                'url' => 'https://www.scielo.br/j/mioc/',
                'country_code' => 'BR',
                'subject_areas' => ['Parasitology', 'Microbiology', 'Tropical Medicine'],
                'is_open_access' => true,
                'oai_base_url' => 'https://www.scielo.br/oai/scielo.php',
                'oai_set_spec' => 'mioc',
                'oai_metadata_prefix' => 'oai_dc',
            ],
            [
                'title' => 'Frontiers in Psychology',
                'issn_print' => null,
                'issn_online' => '1664-1078',
                'publisher' => 'Frontiers Media',
                'url' => 'https://www.frontiersin.org/journals/psychology',
                'country_code' => 'CH',
                'subject_areas' => ['Psychology'],
                'is_open_access' => true,
                'oai_base_url' => 'https://www.frontiersin.org/oai/xml',
                'oai_set_spec' => 'psychology',
                'oai_metadata_prefix' => 'oai_dc',
            ],
            [
                'title' => 'BMC Public Health',
                'issn_print' => null,
                'issn_online' => '1471-2458',
                'publisher' => 'BioMed Central',
                'url' => 'https://bmcpublhealth.biomedcentral.com/',
                'country_code' => 'GB',
                'subject_areas' => ['Public Health'],
                'is_open_access' => true,
                'oai_base_url' => 'https://bmcpublhealth.biomedcentral.com/oai',
                'oai_set_spec' => null,
                'oai_metadata_prefix' => 'oai_dc',
            ],
            [
                'title' => 'JMIR Mental Health',
                'issn_print' => null,
                'issn_online' => '2368-7959',
                'publisher' => 'JMIR Publications',
                'url' => 'https://mental.jmir.org/',
                'country_code' => 'CA',
                'subject_areas' => ['Mental Health', 'Digital Health'],
                'is_open_access' => true,
                'oai_base_url' => 'https://www.jmir.org/oai',
                'oai_set_spec' => 'mental',
                'oai_metadata_prefix' => 'oai_dc',
            ],
        ];

        foreach ($journals as $journalData) {
            Journal::updateOrCreate(
                ['title' => $journalData['title']],
                array_merge($journalData, [
                    'user_id' => $userId,
                    'slug' => Str::slug($journalData['title']),
                    'status' => 'listed',
                    'current_score' => null,
                    'description' => "International journal published by {$journalData['publisher']}.",
                    'target_audience' => ['Academic', 'Researchers'],
                    'publication_languages' => ['en'],
                    'start_year' => 2000,
                    'evaluated_at' => null,
                ])
            );
        }


    }
}
